# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/action_source_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import duration_pb2 as protos_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protos/action_source_config.proto\x12\x06\x66\x61\x63\x61\x64\x65\x1a\x15protos/duration.proto\"\xe7\x01\n\x12\x41\x63tionSourceConfig\x12\x0c\n\x04type\x18\x01 \x01(\t\x12 \n\x18max_history_keys_per_day\x18\x02 \x01(\x05\x12*\n\x10history_duration\x18\x03 \x01(\x0b\x32\x10.facade.Duration\x12\x35\n\x1b\x61\x63tion_deduplication_period\x18\x04 \x01(\x0b\x32\x10.facade.Duration\x12\x1e\n\x16max_values_per_feature\x18\x05 \x01(\x05\x12\x1e\n\x16min_values_per_feature\x18\x06 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.action_source_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACTIONSOURCECONFIG._serialized_start=69
  _ACTIONSOURCECONFIG._serialized_end=300
# @@protoc_insertion_point(module_scope)
