# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context_source_config.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import duration_pb2 as protos_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"protos/context_source_config.proto\x12\x06\x66\x61\x63\x61\x64\x65\x1a\x15protos/duration.proto\"\x88\x01\n\x13\x43ontextSourceConfig\x12\x0c\n\x04type\x18\x01 \x01(\t\x12*\n\x10\x63ontext_lookback\x18\x02 \x01(\x0b\x32\x10.facade.Duration\x12\x37\n\x14peer_feature_configs\x18\x03 \x03(\x0b\x32\x19.facade.PeerFeatureConfig\"\xb7\x02\n\x11PeerFeatureConfig\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tmax_peers\x18\x02 \x01(\x05\x12U\n\x12\x61ggregation_method\x18\x04 \x01(\x0e\x32\x39.facade.PeerFeatureConfig.AttributeValueAggregationMethod\x12\x31\n\x0f\x62ipartite_graph\x18\x03 \x01(\x0b\x32\x16.facade.BipartiteGraphH\x00\"Z\n\x1f\x41ttributeValueAggregationMethod\x12\x13\n\x0f\x41GG_UNSPECIFIED\x10\x00\x12\x12\n\x0e\x41GG_ACCUMULATE\x10\x01\x12\x0e\n\nAGG_LATEST\x10\x02\x42\x1b\n\x19peer_attribute_graph_type\"\x9e\x03\n\x0e\x42ipartiteGraph\x12=\n\x0ftraversal_modes\x18\x01 \x03(\x0e\x32$.facade.BipartiteGraph.TraversalMode\x12#\n\thalf_life\x18\x02 \x01(\x0b\x32\x10.facade.Duration\x12I\n\x15\x65\x64ge_weighting_method\x18\x03 \x01(\x0e\x32*.facade.BipartiteGraph.EdgeWeightingMethod\"Q\n\rTraversalMode\x12\x0c\n\x08TM_UNSET\x10\x00\x12\x11\n\rTM_UNDIRECTED\x10\x01\x12\x0e\n\nTM_FORWARD\x10\x02\x12\x0f\n\x0bTM_BACKWARD\x10\x03\"\x89\x01\n\x13\x45\x64geWeightingMethod\x12\x13\n\x0f\x45WM_UNSPECIFIED\x10\x00\x12\x0e\n\nEWM_LATEST\x10\x01\x12\x19\n\x15\x45WM_DISCOUNTED_LATEST\x10\x02\x12\x16\n\x12\x45WM_SUM_DISCOUNTED\x10\x03\x12\x1a\n\x16\x45WM_LOG_SUM_DISCOUNTED\x10\x04\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.context_source_config_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTEXTSOURCECONFIG._serialized_start=70
  _CONTEXTSOURCECONFIG._serialized_end=206
  _PEERFEATURECONFIG._serialized_start=209
  _PEERFEATURECONFIG._serialized_end=520
  _PEERFEATURECONFIG_ATTRIBUTEVALUEAGGREGATIONMETHOD._serialized_start=401
  _PEERFEATURECONFIG_ATTRIBUTEVALUEAGGREGATIONMETHOD._serialized_end=491
  _BIPARTITEGRAPH._serialized_start=523
  _BIPARTITEGRAPH._serialized_end=937
  _BIPARTITEGRAPH_TRAVERSALMODE._serialized_start=716
  _BIPARTITEGRAPH_TRAVERSALMODE._serialized_end=797
  _BIPARTITEGRAPH_EDGEWEIGHTINGMETHOD._serialized_start=800
  _BIPARTITEGRAPH_EDGEWEIGHTINGMETHOD._serialized_end=937
# @@protoc_insertion_point(module_scope)
