# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/contextualized_actions.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import timestamp_pb2 as protos_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protos/contextualized_actions.proto\x12\x0f\x66\x61\x63\x61\x64\x65.internal\x1a\x16protos/timestamp.proto\"\x9c\x01\n\x15\x43ontextualizedActions\x12\x11\n\tprincipal\x18\x03 \x01(\t\x12\x33\n\x07\x63ontext\x18\x01 \x01(\x0b\x32\".facade.internal.FeaturizedContext\x12;\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32*.facade.internal.FeaturizedActionsBySource\"\x7f\n\x11\x46\x65\x61turizedContext\x12\x43\n\x13\x66\x65\x61tures_per_source\x18\x01 \x03(\x0b\x32&.facade.internal.ContextSourceFeatures\x12%\n\nvalid_from\x18\x02 \x01(\x0b\x32\x11.facade.Timestamp\"d\n\x19\x46\x65\x61turizedActionsBySource\x12\x13\n\x0bsource_type\x18\x01 \x01(\t\x12\x32\n\x07\x61\x63tions\x18\x02 \x03(\x0b\x32!.facade.internal.FeaturizedAction\"\x87\x01\n\x10\x46\x65\x61turizedAction\x12\n\n\x02id\x18\x01 \x01(\x0c\x12\x13\n\x0bresource_id\x18\x04 \x01(\t\x12&\n\x0boccurred_at\x18\x02 \x01(\x0b\x32\x11.facade.Timestamp\x12*\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32\x18.facade.internal.Feature\"X\n\x15\x43ontextSourceFeatures\x12\x13\n\x0bsource_type\x18\x01 \x01(\t\x12*\n\x08\x66\x65\x61tures\x18\x02 \x03(\x0b\x32\x18.facade.internal.Feature\"a\n\x07\x46\x65\x61ture\x12\x0c\n\x04name\x18\x01 \x01(\t\x12@\n\x15\x62\x61g_of_weighted_words\x18\x02 \x01(\x0b\x32\x1f.facade.internal.WeightedTokensH\x00\x42\x06\n\x04type\"@\n\x0eWeightedTokens\x12.\n\x06tokens\x18\x01 \x03(\x0b\x32\x1e.facade.internal.WeightedToken\".\n\rWeightedToken\x12\r\n\x05token\x18\x01 \x01(\x0c\x12\x0e\n\x06weight\x18\x02 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.contextualized_actions_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTEXTUALIZEDACTIONS._serialized_start=81
  _CONTEXTUALIZEDACTIONS._serialized_end=237
  _FEATURIZEDCONTEXT._serialized_start=239
  _FEATURIZEDCONTEXT._serialized_end=366
  _FEATURIZEDACTIONSBYSOURCE._serialized_start=368
  _FEATURIZEDACTIONSBYSOURCE._serialized_end=468
  _FEATURIZEDACTION._serialized_start=471
  _FEATURIZEDACTION._serialized_end=606
  _CONTEXTSOURCEFEATURES._serialized_start=608
  _CONTEXTSOURCEFEATURES._serialized_end=696
  _FEATURE._serialized_start=698
  _FEATURE._serialized_end=795
  _WEIGHTEDTOKENS._serialized_start=797
  _WEIGHTEDTOKENS._serialized_end=861
  _WEIGHTEDTOKEN._serialized_start=863
  _WEIGHTEDTOKEN._serialized_end=909
# @@protoc_insertion_point(module_scope)
