# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/context.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import timestamp_pb2 as protos_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/context.proto\x12\x06\x66\x61\x63\x61\x64\x65\x1a\x16protos/timestamp.proto\"\x81\x01\n\x07\x43ontext\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x11\n\tprincipal\x18\x02 \x01(\t\x12%\n\nvalid_from\x18\x03 \x01(\x0b\x32\x11.facade.Timestamp\x12.\n\x0fpeer_attributes\x18\x04 \x03(\x0b\x32\x15.facade.PeerAttribute\"\xca\x01\n\rPeerAttribute\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x32\n\tdirection\x18\x03 \x01(\x0e\x32\x1f.facade.PeerAttribute.Direction\x12\x0e\n\x06weight\x18\x04 \x01(\x02\x12\x1f\n\x04time\x18\x05 \x01(\x0b\x32\x11.facade.Timestamp\"7\n\tDirection\x12\x0b\n\x07\x44_UNSET\x10\x00\x12\r\n\tD_FORWARD\x10\x01\x12\x0e\n\nD_BACKWARD\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.context_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CONTEXT._serialized_start=57
  _CONTEXT._serialized_end=186
  _PEERATTRIBUTE._serialized_start=189
  _PEERATTRIBUTE._serialized_end=391
  _PEERATTRIBUTE_DIRECTION._serialized_start=336
  _PEERATTRIBUTE_DIRECTION._serialized_end=391
# @@protoc_insertion_point(module_scope)
