# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/directive.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import duration_pb2 as protos_dot_duration__pb2
from protos import action_source_config_pb2 as protos_dot_action__source__config__pb2
from protos import context_source_config_pb2 as protos_dot_context__source__config__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/directive.proto\x12\x06\x66\x61\x63\x61\x64\x65\x1a\x15protos/duration.proto\x1a!protos/action_source_config.proto\x1a\"protos/context_source_config.proto\"\xb1\x03\n\tDirective\x12\x15\n\rmodel_version\x18\x01 \x01(\x05\x12\x32\n\x0e\x61\x63tion_sources\x18\x02 \x03(\x0b\x32\x1a.facade.ActionSourceConfig\x12\x34\n\x0f\x63ontext_sources\x18\x03 \x03(\x0b\x32\x1b.facade.ContextSourceConfig\x12?\n\x12\x64\x61taset_parameters\x18\x04 \x01(\x0b\x32#.facade.Directive.DatasetParameters\x1a\xe1\x01\n\x11\x44\x61tasetParameters\x12)\n\x0fsnapshot_period\x18\x01 \x01(\x0b\x32\x10.facade.Duration\x12.\n\x14snapshot_time_offset\x18\x02 \x01(\x0b\x32\x10.facade.Duration\x12\x32\n*max_num_actions_per_contextualized_actions\x18\x03 \x01(\x05\x12=\n5max_num_contextualized_actions_per_principal_snapshot\x18\x04 \x01(\x05\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.directive_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIRECTIVE._serialized_start=129
  _DIRECTIVE._serialized_end=562
  _DIRECTIVE_DATASETPARAMETERS._serialized_start=337
  _DIRECTIVE_DATASETPARAMETERS._serialized_end=562
# @@protoc_insertion_point(module_scope)
